# Generated by Django 3.2.7 on 2021-11-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='user',
            new_name='student',
        ),
    ]
