# Generated by Django 3.2.7 on 2022-01-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_enrollment_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='exams',
        ),
    ]
