# Generated by Django 3.2.7 on 2022-01-20 10:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_auto_20220103_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examstatus',
            name='score',
            field=models.DecimalField(decimal_places=2, default=Decimal(
                '0.0'), max_digits=5, verbose_name='score'),
        ),
    ]
