# Generated by Django 3.2.7 on 2021-12-14 06:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal(
                '0.0'), max_digits=7, verbose_name='amount'),
        ),
    ]
