# Generated by Django 3.2.7 on 2021-12-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinepayment',
            name='variant',
            field=models.CharField(choices=[(
                'ESEWA', 'esewa')], default='ESEWA', max_length=32, verbose_name='variant'),
        ),
    ]
