# Generated by Django 3.2.7 on 2021-12-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_onlinepayment_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinepayment',
            name='extra_content',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
