# Generated by Django 3.2.7 on 2021-12-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_onlinepayment_extra_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('unpaid', 'unpaid'), ('inprogress', 'inprogress'), ('paid', 'paid'), ('error', 'error')], default='inprogress', max_length=32, verbose_name='status'),
        ),
    ]
