# Generated by Django 3.2.7 on 2021-12-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinepayment',
            name='variant',
            field=models.CharField(choices=[('esewa', 'esewa')], default='esewa', max_length=32, verbose_name='variant'),
        ),
    ]
