# Generated by Django 3.2.7 on 2021-12-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_onlinepayment_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinepayment',
            options={'verbose_name': 'OnlinePayment', 'verbose_name_plural': 'OnlinePayments'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
