# Generated by Django 3.2.7 on 2021-11-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='enrolls',
            field=models.ManyToManyField(blank=True, related_name='parts', to='enrollments.Enrollment', verbose_name='enrolls'),
        ),
    ]
