# Generated by Django 3.2.7 on 2021-11-26 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0002_alter_part_enrolls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='enrolls',
        ),
    ]
