# Generated by Django 3.2.7 on 2021-10-26 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=9840016500, max_length=10, unique=True, validators=[
                                   django.core.validators.RegexValidator(message='Enter a valid phonenumber 9XXXXXXXXX', regex='^9\\d{9}')]),
            preserve_default=False,
        ),
    ]
