# Generated by Django 3.2.7 on 2021-10-30 17:19

import accounts.models
from django.db import migrations, models

def createRoles(apps, schecma_editor):
    Role  = apps.get_model('accounts', 'Role')
    for choice in accounts.models.Role.ROLE_CHOICES:
        obj, created = Role.objects.update_or_create(id=choice[0], defaults={'id':choice[0]})

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'staff'), (4, 'admin')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(blank=True, to='accounts.Role'),
        ),
        migrations.RunPython(createRoles, migrations.RunPython.noop),
    ]
