# Generated by Django 3.2.7 on 2021-11-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211121_1131'),
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(
                blank=True, to='courses.CourseCategory'),
        ),
    ]
