# Generated by Django 3.2.7 on 2022-01-24 03:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_extra_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.image_upload_location),
        ),
    ]
