# Generated by Django 3.2.7 on 2022-05-16 16:21

from django.db import migrations


def create_profile(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Profile = apps.get_model("accounts", "Profile")

    for user in User.objects.all():
        Profile.objects.get_or_create(
            user=user,
            defaults={
                "user": user,
            },
        )


def delete_profile(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220213_0942'),
    ]

    operations = [
        migrations.RunPython(create_profile, delete_profile),
    ]
