# Generated by Django 3.2.7 on 2021-12-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gorkhapatraexam',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mockexam',
            name='id',
        ),
        migrations.AddField(
            model_name='gorkhapatraexam',
            name='exam_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exams.exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mockexam',
            name='exam_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exams.exam'),
            preserve_default=False,
        ),
    ]
