# Generated by Django 3.2.7 on 2021-12-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20211223_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='kind',
            field=models.CharField(choices=[('mock', 'mock'), ('mcq', 'mcq'), ('gorkha', 'gorkha')], default='mock', max_length=32, verbose_name='kind'),
        ),
    ]
