# Generated by Django 3.2.7 on 2021-12-26 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20211130_0951'),
        ('exams', '0004_alter_option_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='category',
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_exam_related', related_query_name='exams_exams', to='courses.course', verbose_name='course'),
        ),
        migrations.DeleteModel(
            name='ExamCategory',
        ),
    ]
