# Generated by Django 3.2.7 on 2021-12-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20211130_0951'),
        ('exams', '0005_auto_20211226_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.ManyToManyField(related_name='exams_exam_related', related_query_name='exams_exams', to='courses.CourseCategory', verbose_name='categories'),
        ),
    ]
