# Generated by Django 3.2.7 on 2021-12-28 08:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exam_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['question'], 'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['exam'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questionstatus',
            options={'ordering': ['-updated_at'], 'verbose_name': 'QuestionStatus', 'verbose_name_plural': 'QuestionStatuss'},
        ),
        migrations.AddField(
            model_name='exam',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='price'),
        ),
    ]
