# Generated by Django 3.2.7 on 2021-12-30 10:33

import courses.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20211228_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, validators=[courses.validators.validate_positive], verbose_name='price'),
        ),
    ]
