# Generated by Django 3.2.7 on 2022-01-03 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_exam_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionStatus',
        ),
    ]
