# Generated by Django 3.2.7 on 2022-01-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_auto_20220103_0451'),
        ('exams', '0009_delete_questionstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upadated_at')),
                ('exam_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_states', to='enrollments.examstatus', verbose_name='examinee')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='exams.question', verbose_name='question')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_choices', to='exams.option', verbose_name='selected_option')),
            ],
            options={
                'verbose_name': 'QuestionStatus',
                'verbose_name_plural': 'QuestionStatuss',
                'ordering': ['-updated_at'],
            },
        ),
    ]
