# Generated by Django 3.2.7 on 2022-01-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_questionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='marks',
            field=models.FloatField(default=0.0, verbose_name='marks'),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.FloatField(default=0.0, verbose_name='marks'),
        ),
    ]
