# Generated by Django 3.2.7 on 2022-01-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_alter_questionstatus_exam_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='neg_marks',
            field=models.FloatField(default=0.0, verbose_name='neg_marks'),
        ),
    ]
