# Generated by Django 3.2.7 on 2022-01-20 10:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_question_neg_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=Decimal(
                '0.0'), max_digits=5, verbose_name='marks'),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=Decimal(
                '0.0'), max_digits=5, verbose_name='marks'),
        ),
        migrations.AlterField(
            model_name='question',
            name='neg_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal(
                '0.0'), max_digits=5, verbose_name='neg_marks'),
        ),
    ]
