# Generated by Django 3.2.7 on 2022-05-01 20:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_auto_20220120_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': [
                'question', 'id'], 'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': [
                'exam', 'id'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=Decimal(
                '2.0'), max_digits=5, verbose_name='marks'),
        ),
        migrations.AlterField(
            model_name='question',
            name='neg_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal(
                '0.4'), max_digits=5, verbose_name='neg_marks'),
        ),
    ]
