# Generated by Django 3.2.7 on 2022-05-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_auto_20220501_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockexam',
            name='timer',
            field=models.DurationField(verbose_name='timer'),
        ),
    ]
