# Generated by Django 3.2.7 on 2021-12-30 10:33

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='price',
            field=models.FloatField(default=0.0, validators=[courses.validators.validate_positive], verbose_name='price'),
        ),
    ]
