# Generated by Django 3.2.7 on 2022-01-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_price'),
        ('notes', '0004_auto_20220127_0307'),
    ]

    operations = [
    ]
