# Generated by Django 3.2.7 on 2022-01-30 08:21

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_merge_0003_alter_note_price_0004_auto_20220127_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='free',
        ),
        migrations.RemoveField(
            model_name='note',
            name='type',
        ),
        migrations.AlterField(
            model_name='note',
            name='price',
            field=models.FloatField(default=0.0, validators=[courses.validators.validate_positive], verbose_name='price'),
        ),
    ]
