# Generated by Django 3.2.7 on 2022-01-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
