# Generated by Django 3.2.7 on 2022-01-21 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_contactus_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
