# Generated by Django 3.2.7 on 2021-11-19 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.coursecategory')),
            ],
            options={
                'verbose_name': 'CourseCategory',
                'verbose_name_plural': 'CourseCategorys',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(verbose_name='link')),
                ('password', models.CharField(help_text='Use\'[algo]$[salt]$[hexdigest]\' or use the < a href="password/">change password form</a>.', max_length=128, verbose_name='password')),
                ('status', models.CharField(choices=[('insession', 'insession'), ('upcoming', 'upcoming'), ('ended', 'ended'), ('cancelled', 'cancelled')], default='upcoming', max_length=32, verbose_name='status')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='detail')),
                ('video', models.URLField(blank=True, null=True, verbose_name='vifeo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.coursecategory', verbose_name='category')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='instructor')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['created_at'],
            },
        ),
    ]
