# Generated by Django 3.2.7 on 2021-11-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='count',
            field=models.IntegerField(default=0, verbose_name='count'),
        ),
        migrations.AddField(
            model_name='course',
            name='detail1',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='detail'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='video'),
        ),
    ]
