# Generated by Django 3.2.7 on 2021-11-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211121_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='count',
        ),
        migrations.AlterField(
            model_name='course',
            name='detail1',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='detail1'),
        ),
    ]
