# Generated by Django 3.2.7 on 2022-01-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(
                blank=True, null=True, upload_to='thumbnails/', verbose_name='thumbnail'),
        ),
    ]
