# Generated by Django 3.2.7 on 2022-01-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='course',
            name='detail1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='video',
        ),
    ]
