# Generated by Django 3.2.7 on 2022-01-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20220119_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='benefit_detail',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='benefit_fire'),
        ),
        migrations.AddField(
            model_name='course',
            name='class_detail',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='class_detail'),
        ),
        migrations.AddField(
            model_name='course',
            name='main_detail',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='main_detail'),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='video'),
        ),
    ]
