# Generated by Django 3.2.7 on 2022-01-20 09:52

import courses.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_benefit_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, validators=[
                                      courses.validators.validate_positive], verbose_name='price'),
        ),
    ]
