# Generated by Django 3.2.7 on 2022-05-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'ordering': [
                'id'], 'verbose_name': 'CourseCategory', 'verbose_name_plural': 'CourseCategorys'},
        ),
    ]
