# Generated by Django 3.2.7 on 2022-05-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_coursecategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='course',
            name='password',
            field=models.CharField(
                blank=True, help_text='Use\'[algo]$[salt]$[hexdigest]\' or use the < a href="password/">change password form</a>.', max_length=128, null=True, verbose_name='password'),
        ),
    ]
