# Generated by Django 3.2.7 on 2022-05-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20220130_1751'),
        ('courses', '0016_alter_course_instructor'),
    ]

    operations = [
    ]
