# Generated by Django 3.2.7 on 2022-05-15 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0018_auto_20220511_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserequest',
            name='votes',
        ),
        migrations.AddField(
            model_name='courserequest',
            name='voters',
            field=models.ManyToManyField(
                blank=True, related_name='course_requests_voters', to=settings.AUTH_USER_MODEL),
        ),
    ]
