# Generated by Django 3.2.7 on 2022-05-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20220515_0520'),
        ('courses', '0019_auto_20220515_0723'),
    ]

    operations = [
    ]
