# Generated by Django 3.2.7 on 2022-01-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20220124_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='free',
        ),
    ]
