# Generated by Django 3.2.7 on 2022-01-30 08:21

import content.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0005_alter_part_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Recorded Video', max_length=200)),
                ('file', models.FileField(
                    upload_to=content.models.recorded_content_location)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='recorded_video', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='recorded_video', to='part.part')),
            ],
        ),
    ]
