# Generated by Django 3.2.7 on 2022-05-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_recordedvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='file',
        ),
        migrations.RemoveField(
            model_name='content',
            name='type',
        ),
        migrations.RemoveField(
            model_name='recordedvideo',
            name='file',
        ),
        migrations.AddField(
            model_name='content',
            name='link',
            field=models.URLField(default='https://www.google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordedvideo',
            name='link',
            field=models.URLField(default='https://www.google.com'),
            preserve_default=False,
        ),
    ]
