# Generated by Django 3.2.7 on 2022-05-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20220515_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedvideo',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
