# Generated by Django 3.2.7 on 2022-05-15 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_recordedvideo_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordedvideo',
            name='detail',
        ),
        migrations.AddField(
            model_name='recordedvideo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordedvideo',
            name='professor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
